<a href="https://colab.research.google.com/github/luffysg/Deep-Learning-Study/blob/master/Deep_Learning_with_Pytorch_deeplizard_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep learning with Pytorch


1.   Tensors: rank, shape, dimension, dtype, device

2.   Tensor creation options with data:
  *   t1 = torch.Tensor(data) # class constructor, use global default dtype, copy data
  *   t2 = torch.tensor(data) # factory function, accpets parameter inputs and return particular type of objects, infer input dtype, copy data
  *   t3 = torch.as_tensor(data) # factory function, infer input data type, share data, accpet any array like python data
  *   t4 = torch.from_numpy(data) # factory function, infer input dtype, share data, accept only numpy array

3.   Tensor creation options without data:
  *   torch.eyes(), torch.zeros(), torch.ones(), torch.rand()

4.   Essential tensor operations: flatten, reshape, squeeze
  *   t.size(), t.shape, t.numel()
  *   t.reshape(2,3), t.reshape(3,-1): -1 is to let program to figure out the number of elements needed
  *   flatten a tensor: t.reshape(-1), t.flatten(), t.view(t.numel())
  *   t.flatten(start_dim =1) # flatting skip 1st dim, starting from the 2nd dim, usually done for image tensors
  *   CNN tensors [B,C,H,W]: batch size, color channel, height and width

5.   broadcasting and element wise operations:
  *   element-wise operation can be done only on tensors with the same shape
  *   scalar value is rank 0 tensor
  *   broadcasting: copy one or more axes of my tensor to allow it to be the same shape as the other tensor

6.   Argmax and tensor reduction operations:
  *   t.prod(). t.mean(), t.sum(), t.std()
  *   t.mean(dim = 0)








In [0]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.3.1


In [3]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130


In [4]:
torch.cuda.is_available() #go to edit > notebook settings >set hardware accelerator to GPU

True

In [3]:
torch.cuda.get_device_name(0)

'Tesla P100-PCIE-16GB'

##Tensors

In [6]:
# 1-d
a = [1,2,3,4]
a[2]

3

In [8]:
#2-d
b = [
     [1,2,3],
     [4,5,6],
     [7,8,9]
]

b[2][0]

7

In [11]:
#rank of a tensor refers to the number of dimensions present with the tensor
# tells us how many indices we need to access individual element of the tensor
b[2]
b[2][1]


8

In [0]:
#shape defines the length of each axis, indicates the number of indices available along each axis
t = torch.tensor(b)

In [13]:
t.shape

torch.Size([3, 3])

In [14]:
# the rank of a tensor is equal to the length of its shape
len(t.shape)

2

In [15]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Examples using tensors rank/shape

In [0]:
# Images
#[B,C,H,W] Batch size, color channel: RGB, height, width 

Tensor class

In [17]:
t = torch.Tensor()
type(t)

torch.Tensor

In [18]:
#1. Tensors contain data of a uniform type
#2. Tensor computations between tensors depend on the dtype and the device
print(t.dtype) 
print(t.device) 
print(t.layout)

torch.float32
cpu
torch.strided


In [21]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [0]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.0,2.0,3.0])

In [23]:
print(t1.dtype)
print(t2.dtype)

torch.int64
torch.float32


In [24]:
t1+t2 #suppose to have an error here?

tensor([2., 4., 6.])

In [0]:
t1 = torch.tensor([1,2,3])
t2 = t1.cuda()

In [28]:
print(t1.device)
print(t2.device)

cpu
cuda:0


In [27]:
t1 + t2

RuntimeError: ignored

##Tensor creation options using data

In [29]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [30]:
# torch.Tensor() creates a class/object? dtype is float
torch.Tensor(data)

tensor([1., 2., 3.])

In [31]:
#factory function, keep same integer dtype
torch.tensor(data)

tensor([1, 2, 3])

In [32]:
#keep same integer dtype
torch.as_tensor(data)

tensor([1, 2, 3])

In [33]:
#keep same integer dtype
torch.from_numpy(data)

tensor([1, 2, 3])

##Tensor creation options without data

In [34]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [35]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [36]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [37]:
torch.rand(2,2)

tensor([[0.5769, 0.3807],
        [0.3848, 0.7293]])

##Tensor creation: best option

Best option 

1.   For daily use: torch.tensor();
2.   For memroy sharing: torch.as_tensor(), accepts any array like python data structure while torch.from_numpy() accpets only numpy array


 

*   t1 = torch.Tensor(data) # class constructor, use global default dtype, copy data

*   t2 = torch.tensor(data) # factory function, accpets parameter inputs and return particular type of objects, infer input dtype, copy data
*   t3 = torch.as_tensor(data) # factory function, infer input data type, share data, accpet any array like python data


*   t4 = torch.from_numpy(data) # factory function, infer input dtype, share data, accept only numpy array







In [0]:
data = np.array([1,2,3])

In [0]:
t1 = torch.Tensor(data) # class constructor
t2 = torch.tensor(data) # factory function, accpets parameter inputs and return particular type of objects
t3 = torch.as_tensor(data) # also factory function
t4 = torch.from_numpy(data) # factory function

In [5]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [6]:
print(t1.dtype) #constructor uses the global default dtype values when constructing a tensor
print(t2.dtype) #factory function infers the data type, type inference based on input data
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [7]:
torch.get_default_dtype()

torch.float32

In [8]:
#specify the dtype using factory function, however constructor does NOT have
torch.tensor(np.array([1,2,3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [0]:
#sharing memory for performance: copy vs share
#1) share data: torch.as_tensor(), torch.from_numpy()
#2) copy data: torch.tensor(), torch.Tensor()
data[0] = 0
data[1]= 0
data[2]=0

In [10]:
#1st 2 methods creates a copy of original numpy array
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [11]:
# last 2 methods share the data in memory with the numpy array
print(t3)
print(t4)

tensor([0, 0, 0])
tensor([0, 0, 0])


##Essential tensor operations: flatten, reshape, squeeze


1.   Reshaping operations
2.   Element-wise operations
3.   Reduction operations
4.   Access operations



In [0]:
t = torch.tensor([
                  [1,1,1,1],
                  [2,2,2,2],
                  [3,3,3,3]
], dtype=torch.float32)

In [13]:
t.size() #size is a method

torch.Size([3, 4])

In [14]:
t.shape #shape is an attribute

torch.Size([3, 4])

In [15]:
len(t.shape)

2

In [16]:
torch.tensor(t.shape).prod()

tensor(12)

In [17]:
t.numel() #number of element

12

In [18]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [19]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [20]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [21]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [22]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [23]:
# squeeze: remove all the axes to have a length of 1, turn it to a lower rank tensor
#unsqueeze: adds a dimension with a length of 1
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [24]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [26]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [0]:
# construct a flatten function
def flatten(t):
  t = t.reshape(1,-1) # -1 lets the reshape function figures out the number
  t = t.squeeze()
  return t

In [7]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [8]:
t.reshape(-1)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [21]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [22]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

## Concatenating tensors

In [0]:
t1 = torch.tensor([
                   [1,2],
                   [3,4]
])
t2 = torch.tensor([
                   [5,6],
                   [7,8]
])

In [10]:
#combine t1 and t2 row-wise (axis = 0)
torch.cat((t1,t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [11]:
#combine t1 and t2 column-wise (axis=1) like this:
torch.cat((t1,t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

###CNN flatten operation visualized - Tensor Batch Processing for Deep Learning


In [0]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
  [2,2,2,2],
  [2,2,2,2],
  [2,2,2,2],
  [2,2,2,2]
])

t3 = torch.tensor([
  [3,3,3,3],
  [3,3,3,3],
  [3,3,3,3],
  [3,3,3,3]
])

In [13]:
t = torch.stack((t1,t2,t3)) #stack 3 tensors along a new axis
t.shape

torch.Size([3, 4, 4])

In [14]:
t # 3 represents batch size, 4 represents height and 4 represents width

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [16]:
# add a color channel
t = t.reshape(3,1,4,4) #batch size, color, height, width
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [17]:
t[0] # 1st image

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [18]:
t[0][0] # 1st color channel in the 1st image

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [19]:
t[0][0][0] # 1st row of pixels in the 1st color channel of 1st image

tensor([1, 1, 1, 1])

In [20]:
t[0][0][0][0] # 1st pixel of 1st row, 1st color of 1st image

tensor(1)

In [23]:
# we want to flatten each image not all 3 images within one batch
t.flatten(start_dim =1).shape

torch.Size([3, 16])

In [25]:
t.flatten(start_dim =1) # flatting skip 1st dim, starting from the 2nd dim

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [26]:
t.reshape(3,-1) # achieve the same flattening

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

##Tensor: broadcasting and element-wise operations

In [0]:
t1 = torch.tensor([
                   [1,2],
                   [3,4]
], dtype= torch.float32)

t2 = torch.tensor([
                   [9,8],
                   [7,6]
], dtype=torch.float32)






*   element-wise operation can be done only on tensors with the same shape
*   scalar value is rank 0 tensor
*   broadcasting: copy one or more axes of my tensor to allow it to be the same shape as the other tensor





In [28]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [29]:
t1 +2

tensor([[3., 4.],
        [5., 6.]])

In [30]:
t1 -2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [31]:
t1 *2

tensor([[2., 4.],
        [6., 8.]])

In [32]:
t1/2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [33]:
# see how does broadcasting works
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [34]:
t1 +2

tensor([[3., 4.],
        [5., 6.]])

In [35]:
t1 + torch.tensor(np.broadcast_to(2, t1.shape), dtype = torch.float32)

tensor([[3., 4.],
        [5., 6.]])

In [0]:
# 2 tensors with different shape and broadcasting still works
t1 = torch.tensor([
                   [1,1],
                   [1,1]
])

t2 = torch.tensor([2,4], dtype = torch.float32)

In [37]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

In [38]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

##Argmax  and Reduction Tensor ops

A reduction operation on a tensor is an operation that reduces the number of elements contained within the tensor: sum, prod, mean, std

In [46]:
t = torch.tensor([
                  [0,1,0],
                  [2,0,2],
                  [0,3,0]
], dtype = torch.float32)
t.sum()

tensor(8.)

In [40]:
t.numel()

9

In [41]:
t.sum().numel()

1

In [42]:
t.sum().numel() < t.numel()

True

In [43]:
t.sum()

tensor(8)

In [44]:
t.prod()

tensor(0)

In [47]:
t.mean()

tensor(0.8889)

In [48]:
t.std()

tensor(1.1667)

In [0]:
t = torch.tensor([
                  [1,1,1,1],
                  [2,2,2,2],
                  [3,3,3,3]
], dtype = torch.float32)

In [50]:
t.sum(dim =0) #

tensor([6., 6., 6., 6.])

In [52]:
#above and below are the same
t[0] + t[1] + t[2]

tensor([6., 6., 6., 6.])

In [51]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [0]:
#argmax reduction
t = torch.tensor([
                  [1,0,0,2],
                  [0,3,3,0],
                  [4,0,0,5]
], dtype = torch.float32)


In [4]:
t.max()

tensor(5.)

In [5]:
t.argmax() # return the index of maximum value from the flattened tensor, see below for the flattened tensor

tensor(11)

In [6]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [7]:
t.max(dim = 0) # along the 1st dimension

torch.return_types.max(values=tensor([4., 3., 3., 5.]), indices=tensor([2, 1, 1, 2]))

In [8]:
t.argmax(dim =0) # along the 1st dimension

tensor([2, 1, 1, 2])

In [9]:
t.max(dim = 1) # along the 2nd dimension

torch.return_types.max(values=tensor([2., 3., 5.]), indices=tensor([3, 2, 3]))

In [10]:
t.argmax(dim = 1) # along the 2nd dimension

tensor([3, 2, 3])

In [0]:
t = torch.tensor([
                  [1,2,3],
                  [4,5,6],
                  [7,8,9]
], dtype = torch.float32)

In [14]:
t.mean()

tensor(5.)

In [15]:
# item() method only applies to tensor with single element 
t.mean().item()

5.0

In [16]:
#convert to a list
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [18]:
# convert to a numpy array
t.mean(dim =0).numpy()

array([4., 5., 6.], dtype=float32)